theme: jekyll-theme-cayman
title: Les carnets de bord du Challenge Data 6
description: Revivez l'expérience d'écriture d'un article de data-journalisme avec le récit des étudiants de Sciences Po Saint-Germain-En-Laye
